version: '0.0.1'

services:
  mongodb:
    image: mongo:latest
    container_name: app_mongo
    restart: always
    env_file:
      - .env
      - .env.production
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./database:/data/db
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    # volumes:
    # - ./db:/data/db
    networks:
      - private

  app:
    image: express-app
    build:
      context: .
    depends_on:
      - mongodb
    # restart: unless-stopped
    restart: always
    env_file:
      - .env
      - .env.production
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    ports:
      - 3030:3030
    stdin_open: true
    tty: true
    networks:
      - public
      - private

  # next:
  #   image: next-js-test:0.0.1
  #   restart: always
  #   depends_on:
  #     - app
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - private
  #     - public

volumes:
  db_data:
    driver: local

networks:
  public:
  private:
    driver: bridge
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/
  #     ME_CONFIG_BASICAUTH: false
