
###

POST http://localhost:3030/api/user HTTP/1.1
Authorization: token xxx
content-type: application/json

{
  "userId": "admin1",
  "email" : "admin1@gmail.com",
  "username" : "suyeon",
  "password": "1234!",
   "birth": "19890622",
   "phone": "01043140622",
   "employeeId": null
}


### getUser
GET http://localhost:3030/api/user/admin1 HTTP/1.1
content-type: application/json

### deleteUser
DELETE http://localhost:3030/api/user/admin1 HTTP/1.1
content-type: application/json


####
GET http://localhost:3030/api/users HTTP/1.1
Authorization: token xxx
content-type: application/json

