## signup

POST http://localhost:3030/auth/sign-up HTTP/1.1
Authorization: token xxx
content-type: application/json

{
  "userId": "admin",
  "email" : "admin@gmail.com",
  "username" : "suyeon.you",
  "password": "1234!",
   "birth": "19890622",
   "phone": "01043140622",
   "employeeId": null
}

### login
POST http://localhost:3030/auth/sign-in
content-type: application/json

{
  "userId": "admin",
  "password": "1234!"
}

### check

GET http://localhost:3030/auth/sign-up/check?userId=admin HTTP/1.1
content-type: application/json


